
[[constraint]]
  name = "github.com/lab259/graphql"
  branch = "swapedrefs"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
  unused-packages = true
